### ISSUE TITLE
Web application 

### ISSUE THREAD

**Issue by AniruddhaGawali** [AniruddhaGawali/Spend-Wise#23]
- create a web app for the application
- the font and icon use in webapp should be same as app 
- font: poppoins
- icon : material design icons (https://pictogrammers.com/docs/library/mdi/getting-started/react/)
- create landing page 
- create T&C page
- for create web application add a folder in main directory name web

**Comment by Mohitraut07** [comment]
please assign me I would like to work on this.

**Comment by AniruddhaGawali** [comment]
@Mohitraut07 i have assign it to any issue contact here
