### ISSUE TITLE
New: create update account api

### ISSUE THREAD

**Issue by AniruddhaGawali** [AniruddhaGawali/Spend-Wise#5]
Create an api to edit or update account 
- its take the  jwt token and auth it and return accound id
- edit the name of account
- edit the money or balance of account 
- edit the type of account cash or bank 

please take help of edit transaction api to know well
and the api should have end point "api/account/update"

**Comment by Freakyab** [comment]
Assign me

**Comment by AniruddhaGawali** [comment]
@Freakyab i have assign it to u

need any installation guide for app for testing contact me
